### ISSUE TITLE
sched_getaffinity for mac

### ISSUE THREAD

**Issue by diveu** [AlessioZanga/PyEEGLab#25]
Hi! I'm trying to use your dataset on Mac OS X, and sched_getaffinity is not included there. Is there any hotfix for this? I'm considering using simple Pool(2) instead of len you provided, is that correct?

**Comment by AlessioZanga** [comment]
Hi! From a quick research multiprocessing.cpu_count() seems to be the simplest way to go, but I'm not using Mac OS X so if you could try that and then do a pull request it would be wonderful :)

**Comment by diveu** [comment]
Thanks a lot! I'll send a PR shortly
