### ISSUE TITLE
About data processing: Dumping cache file 

### ISSUE THREAD

**Issue by aqibsaeed** [AlessioZanga/PyEEGLab#29]
Hi Alessio,

Thanks for open sourcing the library. I am trying to process it **tuh_eeg_seizure** dataset. But the process stuck at _Dumping cache file_ . Any ideas what's causing this? if it is normal how long shall I wait for it to finish? Here's the code snippet I used:

```
path = "./tuh_eeg_seizure/v1.5.2/edf/train"
tuh_artifact_dataset = TUHEEGSeizureDataset(path)

preprocessing = Pipeline([
    CommonChannelSet(),
    LowestFrequency(),
    ToDataframe(),
    MinMaxCentralizedNormalization(),
    DynamicWindow(8),
    ToNumpy()
])
```

**Comment by aqibsaeed** [comment]
After installing the latest version from Github, I am getting following errors:

Traceback (most recent call last):
  File "eeg.py", line 16, in <module>
    dataset = tuh_artifact_dataset.set_pipeline(preprocessing).load()
  File "/opt/conda/lib/python3.7/site-packages/pyeeglab/dataset/dataset.py", line 23, in load
    return self.cache.load(dataset, self.loader, self.pipeline)
  File "/opt/conda/lib/python3.7/site-packages/pyeeglab/cache/cache.py", line 61, in load
    data = pipeline.run(data)
  File "/opt/conda/lib/python3.7/site-packages/pyeeglab/pipeline/pipeline.py", line 70, in run
    data = np.array(data)
ValueError: could not broadcast input array from shape (8,9465,19) into shape (8)

**Comment by AlessioZanga** [comment]
Hi! 

The "Dumping cache file" step require computing the cache key, which is like an hash of the current status of the dataset, depending on your hardware configuration it should take a couple of minutes (the Seizure dataset is quite big).

Unfortunately, I'm not able to reproduce the error that you reported, I'll investigate in the next week!

**Comment by aqibsaeed** [comment]
"Dumping cache file" issue is resolved. 
Is there any way to fix the last issue: "ValueError: could not broadcast input array from shape (8,9465,19) into shape (8)"

**Comment by AlessioZanga** [comment]
The ValueError is due to the fact that this pipeline split an event in a EEG record in 8 frames of different length, which cannot be transformed in a single Numpy array since they have different dimensions, please consider a StaticWindow approach to obtain same-length frames or remove the ToNumpy preprocessor

**Comment by aqibsaeed** [comment]
Thanks. Could you please explain what frames are? given a length of a frame, aren't frames be computed automatically?

**Comment by aqibsaeed** [comment]
With this setting:

```
path = "./data/tuh_eeg_seizure/v1.5.2/edf/train"

tuh_dataset = TUHEEGSeizureDataset(path)

preprocessing = Pipeline([
    CommonChannelSet(),
    LowestFrequency(),
    ToDataframe(),
    MinMaxCentralizedNormalization(),
    DynamicWindow(5),
])

dataset = tuh_dataset.set_pipeline(preprocessing).load()
data, labels = dataset['data'], dataset['labels']
```
There is this error:
 Reason: 'error("'i' format requires -2147483648 <= number <= 2147483647")'

**Comment by aqibsaeed** [comment]
Any pointers on how this can be fixed?

**Comment by aqibsaeed** [comment]
I resolved this issue through using a VM instance with large memory and high number of CPUs. 
Processing locally on a standard laptop will take a lot of time in my opinion.
