### ISSUE TITLE
exclude channels 03_tcp_ar_a

### ISSUE THREAD

**Issue by lienz** [AlessioZanga/PyEEGLab#31]
https://github.com/AlessioZanga/PyEEGLab/blob/a88f62aa4fe67b659a81ade7019be517304acebd/pyeeglab/dataset/tuh_eeg_artifact/tuh_eeg_artifact_loader.py#L11

Shouldn't the second element of the list be 03_tcp_ar_a, as specified in the directory tree of the artifact dataset? https://www.isip.piconepress.com/projects/tuh_eeg/downloads/tuh_eeg_artifact/v1.0.0/edf/

**Comment by AlessioZanga** [comment]
Yep, an other typo, thanks! This repo is under heavy refactoring :)
