### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by NazarAli** [AlessioZanga/PyEEGLab#33]
**I have error when try run example**

`
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Process finished with exit code -1
`

**Comment by NazarAli** [comment]
i try  add this 
`
if __name__ == '__main__':
    dataset = TUHEEGAbnormalDataset()
    dataset.download(user='nedc_tuh_eeg', password='nedc_tuh_eeg')
    dataset.index()
`

this error appear 

`
PS C:\Users\nazar\Desktop\test> & C:/ProgLang/Python3.8.5/python.exe c:/Users/nazar/Desktop/test/main.py
2020/10/26 11:57:15    INFO: Init dataset 'Temple University Hospital EEG Abnormal Dataset'@'v2.0.0' at 'C:\Users\nazar\Desktop\test\data\tuh_eeg_abnormal\v2.0.0'
2020/10/26 11:57:15   DEBUG: Make .pyeeglab directory
2020/10/26 11:57:15   DEBUG: Make .pyeeglab/cache directory
2020/10/26 11:57:15   DEBUG: Set MNE log .pyeeglab/mne.log
2020/10/26 11:57:15   DEBUG: Make index session
2020/10/26 11:57:15    INFO: Index data set directory
2020/10/26 11:57:25   DEBUG: Add file b8922c83-9291-5ea0-b8fc-1a2987781dff to index
2020/10/26 11:57:25   DEBUG: Add file 7182adef-56ab-5853-861e-77fd8c6ec950 to index
2020/10/26 11:57:26    INFO: Commit insertions to index
2020/10/26 11:57:26    INFO: Index data set completed
2020/10/26 11:57:26   DEBUG: Init default query
2020/10/26 11:57:26   DEBUG: SQL query representation: 'SELECT file.uuid AS file_uuid, file.path AS file_path, file.extension AS file_extension, metadata.file_uuid AS metadata_file_uuid, metadata.duration AS metadata_duration, metadata.channels_set AS metadata_channels_set, metadata.channels_reference AS metadata_channels_reference, metadata.sampling_frequency AS metadata_sampling_frequency, metadata.max_value AS metadata_max_value, metadata.min_value AS metadata_min_value, annotation.uuid AS annotation_uuid, annotation.file_uuid AS annotation_file_uuid, annotation."begin" AS annotation_begin, annotation."end" AS annotation_end, annotation.label AS annotation_label FROM file JOIN metadata ON file.uuid = metadata.file_uuid JOIN annotation ON file.uuid = annotation.file_uuid WHERE 1 = 1 AND 1 = 1 AND annotation."end" - annotation."begin" >= ?'
2020/10/26 11:57:26    INFO: Download started, it will take some time
Traceback (most recent call last):
  File "c:/Users/nazar/Desktop/test/main.py", line 10, in <module>
    dataset.download(user='nedc_tuh_eeg', password='nedc_tuh_eeg')
  File "C:\ProgLang\Python3.8.5\lib\site-packages\pyeeglab\dataset\tuh_eeg\abnormal_dataset.py", line 41, in download
    rsync(self.path, user, password, "tuh_eeg_abnormal", self.version)
  File "C:\ProgLang\Python3.8.5\lib\site-packages\pyeeglab\dataset\tuh_eeg\utils.py", line 18, in rsync
    process = subprocess.Popen(
  File "C:\ProgLang\Python3.8.5\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgLang\Python3.8.5\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

**Comment by AlessioZanga** [comment]
Thank you for reporting this error. Actually, it seems that you are working on a Win32 platform. Unfortunately, this packege has not been tested yet on Windows platforms, but as far as I can see from:

> File "C:\ProgLang\Python3.8.5\lib\subprocess.py", line 1307, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] The system cannot find the file specified

the problem seems related to the subprocess component, which is platform dependant.

I'll try in the following days to debug the issue!

**Comment by NazarAli** [comment]
thank my dear i try run the code in Ubuntu
this error appear 
`
Download started, it will take some time
Host key verification failed.
`

**Comment by NazarAli** [comment]
is there any help for error
`Host key verification failed.`

**Comment by AlessioZanga** [comment]
It seems related to your OS configuration, such as host key changed from the last time a connection was made, try to remove the old entries from ~/.ssh/known_hosts and reconnect, or switch to manual download from the TUH repository.
